services:
  - type: web
    name: talent-bridge-backend
    env: docker
    dockerContext: Backend
    dockerfilePath: Backend/Dockerfile
    plan: free
    branch: main
    numInstances: 1
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
    healthCheckPath: /admin/login/

  - type: worker
    name: talent-bridge-worker
    env: docker
    dockerContext: Backend
    dockerfilePath: Backend/Dockerfile
    plan: free
    branch: main
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromService:
          type: web
          name: talent-bridge-backend
          envVarKey: DATABASE_URL
      - key: REDIS_URL
        fromService:
          type: web
          name: talent-bridge-backend
          envVarKey: REDIS_URL
      - key: DISABLE_COLLECTSTATIC
        value: "1"
    dockerCommand: python -m celery -A talent_bridge worker -l info